# Generated by Django 4.0.6 on 2022-07-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
